group: deprecated-2017Q4

dist: trusty

sudo: required

language: c

compiler:
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq xz-utils autoconf automake bison build-essential flex gawk gettext gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils libncurses5-dev autopoint curl
    - sudo cp -f ./trunk/tools/travis/* /opt && sudo bash ./trunk/tools/travis_ci_build_trig.sh

before_script:
    - sudo mkdir -p /opt/rt-n56u/ && sudo mkdir -p /opt/images/
    - sudo rm -rf toolchain-mipsel/
    - sudo mv -f * .[^.]* /opt/rt-n56u
    - cd /opt/rt-n56u && sudo git clone --depth=1 https://github.com/hanwckf/padavan-toolchain.git toolchain-mipsel && sudo chmod u+x ./toolchain-mipsel/toolchain-3.4.x/bin/*
    - ls -Alh /opt/rt-n56u
    - cd /opt/rt-n56u/trunk/

script:
    - sudo bash ./build_firmware_nohup NEWIFI3 && sudo cp -f images/*.trx /opt/images

after_script:
    - GIT_VERSION=`git rev-parse --short=7 HEAD 2>/dev/null` && [ -n "$GIT_VERSION" ] && image_name=images_mt7620_$GIT_VERSION || image_name=images_mt7620
    - cd /opt/images && sudo bash -c "md5sum * > md5sum.txt" && sudo XZ_OPT=-9 tar cvJf ${image_name}.tar.xz ./*
    - curl --upload-file ./${image_name}.tar.xz https://transfer.sh/${image_name}.tar.xz


